// bus_route_arduino.ino
// AUTO-GENERATED by gen_rom.py  � do not edit by hand.
//
// Arduino port of the DE1-SoC bus route LED map display.
// Requires: FastLED library (Sketch > Include Library > Manage Libraries > FastLED)
//
// Works on: Arduino UNO, Arduino Mega 2560, or compatible.
//
// Wiring (minimal � only 2 wires needed):
//   WS2812B DIN  -> Pin 6  (through 300-470 ohm resistor)
//   WS2812B GND  -> GND
//   WS2812B 5V   -> external 5V supply (do NOT power from Arduino 5V pin)
//
// Demo mode is ALWAYS active: cycles through all 32 states automatically
// (4 scenarios x 8 time slots, 10 seconds each, ~5 minute full cycle).
//
// State order: Sunny-Sep Early Morning -> AM Peak -> ... -> Night,
//   then Heavy Rain Nov Early Morning -> ... -> Named Storm Jan Night.

#include <FastLED.h>
#include <avr/pgmspace.h>

#define NUM_LEDS           156
#define DATA_PIN             6
#define LED_TYPE       WS2812B
#define COLOR_ORDER        GRB
#define BRIGHTNESS         200

// Timing (milliseconds)
#define DWELL_MS          2000   // time spent at each stop
#define MOVE_MS            150   // time per LED step while travelling
#define DEMO_INTERVAL_MS 30000   // 30 seconds per state (32 states total = ~16 min full cycle)

#define N_STOPS          15
#define NUM_PATHS        53
#define TOTAL_PATH_LEN   917
#define MAX_ROUTE_LEN    11

// ============================================================
// PROGMEM data tables (generated from route_plan.json)
// ============================================================

static const uint8_t PROGMEM stop_leds[N_STOPS] = {
    106, 114, 33, 70, 78, 25, 65, 58, 95, 21, 50, 44, 142, 11, 1
};

// demand_data[addr][stop]: bits[1:0]=demand_level, bits[3:2]=bus_route(1=bus0/1,2=bus1)
static const uint8_t PROGMEM demand_data[32][N_STOPS] = {
    {6, 4, 5, 5, 8, 8, 6, 5, 5, 8, 4, 4, 8, 8, 8},  // [ 0] Sunny Early Morning,
    {7, 5, 7, 6, 9, 8, 7, 6, 7, 8, 6, 6, 9, 8, 8},  // [ 1] Sunny AM Peak,
    {7, 8, 6, 6, 4, 8, 7, 5, 6, 8, 5, 5, 8, 8, 8},  // [ 2] Sunny Mid Morning,
    {7, 8, 6, 5, 4, 8, 6, 5, 6, 8, 5, 5, 8, 8, 8},  // [ 3] Sunny Lunch,
    {7, 8, 7, 6, 4, 8, 7, 6, 7, 8, 6, 5, 8, 8, 8},  // [ 4] Sunny Afternoon,
    {7, 4, 7, 6, 8, 8, 7, 6, 7, 8, 6, 6, 8, 8, 8},  // [ 5] Sunny PM Peak,
    {7, 8, 7, 6, 4, 8, 7, 6, 7, 8, 6, 5, 8, 8, 8},  // [ 6] Sunny Evening,
    {6, 4, 5, 5, 0, 0, 6, 5, 5, 0, 4, 4, 8, 0, 0},  // [ 7] Sunny Night,
    {6, 8, 6, 5, 4, 8, 6, 5, 5, 8, 5, 4, 8, 8, 8},  // [ 8] Rain Early Morning,
    {7, 9, 7, 6, 5, 9, 7, 6, 7, 8, 6, 6, 9, 8, 9},  // [ 9] Rain AM Peak,
    {7, 4, 7, 6, 8, 8, 7, 6, 6, 8, 5, 5, 8, 8, 8},  // [10] Rain Mid Morning,
    {7, 4, 6, 5, 8, 8, 7, 5, 6, 8, 5, 5, 8, 8, 8},  // [11] Rain Lunch,
    {7, 4, 7, 6, 8, 8, 7, 6, 7, 8, 6, 6, 8, 8, 8},  // [12] Rain Afternoon,
    {7, 4, 7, 6, 8, 8, 7, 6, 7, 8, 6, 6, 8, 8, 8},  // [13] Rain PM Peak,
    {7, 8, 7, 6, 4, 8, 7, 6, 7, 8, 6, 6, 8, 8, 8},  // [14] Rain Evening,
    {6, 4, 6, 5, 8, 8, 6, 5, 6, 0, 5, 4, 8, 0, 8},  // [15] Rain Night,
    {6, 8, 5, 5, 4, 0, 6, 4, 5, 8, 4, 4, 8, 0, 8},  // [16] Festival Early Morning,
    {7, 8, 7, 5, 8, 8, 7, 5, 6, 8, 5, 5, 4, 4, 4},  // [17] Festival AM Peak,
    {7, 4, 6, 5, 8, 8, 7, 5, 6, 8, 5, 5, 8, 8, 8},  // [18] Festival Mid Morning,
    {7, 4, 7, 5, 8, 8, 6, 5, 6, 8, 5, 5, 8, 0, 0},  // [19] Festival Lunch,
    {7, 4, 7, 6, 8, 8, 7, 5, 7, 8, 5, 5, 8, 8, 8},  // [20] Festival Afternoon,
    {7, 4, 7, 6, 8, 8, 7, 5, 7, 8, 5, 5, 8, 0, 8},  // [21] Festival PM Peak,
    {7, 8, 7, 6, 4, 8, 7, 5, 6, 0, 5, 5, 8, 0, 8},  // [22] Festival Evening,
    {7, 0, 6, 5, 4, 0, 6, 5, 6, 0, 5, 4, 8, 0, 0},  // [23] Festival Night,
    {6, 4, 5, 5, 8, 8, 5, 5, 5, 8, 4, 4, 8, 8, 8},  // [24] Storm Early Morning,
    {7, 9, 7, 6, 5, 8, 7, 6, 7, 8, 6, 6, 9, 8, 8},  // [25] Storm AM Peak,
    {6, 8, 6, 5, 4, 8, 6, 5, 6, 8, 5, 5, 8, 8, 8},  // [26] Storm Mid Morning,
    {6, 4, 6, 5, 8, 8, 6, 5, 6, 8, 5, 5, 8, 8, 8},  // [27] Storm Lunch,
    {7, 4, 7, 6, 8, 8, 7, 6, 6, 8, 5, 5, 8, 8, 8},  // [28] Storm Afternoon,
    {7, 8, 7, 6, 4, 8, 7, 6, 6, 8, 5, 5, 8, 8, 8},  // [29] Storm PM Peak,
    {7, 4, 6, 6, 8, 8, 7, 6, 6, 8, 5, 5, 8, 8, 8},  // [30] Storm Evening,
    {5, 4, 5, 4, 0, 0, 5, 4, 4, 0, 4, 4, 4, 0, 0}  // [31] Storm Night
};

// route_stops_pgm[addr][bus][step] = LED index of stop at that step
static const uint8_t PROGMEM route_stops_pgm[32][2][11] = {
    {{106, 33, 65, 58, 95, 44, 50, 70, 114, 0, 0}, {142, 11, 1, 78, 25, 21, 0, 0, 0, 0, 0}},  // [ 0] Sunny Early Morning,
    {{106, 33, 65, 58, 95, 44, 50, 70, 114, 0, 0}, {142, 11, 1, 78, 25, 21, 0, 0, 0, 0, 0}},  // [ 1] Sunny AM Peak,
    {{106, 33, 65, 58, 95, 44, 50, 70, 78, 0, 0}, {142, 11, 1, 114, 25, 21, 0, 0, 0, 0, 0}},  // [ 2] Sunny Mid Morning,
    {{106, 33, 65, 58, 95, 44, 50, 70, 78, 0, 0}, {142, 11, 1, 114, 25, 21, 0, 0, 0, 0, 0}},  // [ 3] Sunny Lunch,
    {{106, 33, 65, 58, 95, 44, 50, 70, 78, 0, 0}, {142, 11, 1, 114, 25, 21, 0, 0, 0, 0, 0}},  // [ 4] Sunny Afternoon,
    {{106, 33, 65, 58, 95, 44, 50, 70, 114, 0, 0}, {142, 11, 1, 78, 25, 21, 0, 0, 0, 0, 0}},  // [ 5] Sunny PM Peak,
    {{106, 33, 65, 58, 95, 44, 50, 70, 78, 0, 0}, {142, 11, 1, 114, 25, 21, 0, 0, 0, 0, 0}},  // [ 6] Sunny Evening,
    {{106, 33, 65, 58, 95, 44, 50, 70, 114, 0, 0}, {142, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},  // [ 7] Sunny Night,
    {{106, 33, 65, 58, 95, 44, 50, 70, 78, 0, 0}, {142, 11, 1, 114, 25, 21, 0, 0, 0, 0, 0}},  // [ 8] Rain Early Morning,
    {{106, 33, 65, 58, 95, 44, 50, 70, 78, 0, 0}, {142, 11, 1, 21, 25, 114, 0, 0, 0, 0, 0}},  // [ 9] Rain AM Peak,
    {{106, 33, 65, 58, 95, 44, 50, 70, 114, 0, 0}, {142, 11, 1, 78, 25, 21, 0, 0, 0, 0, 0}},  // [10] Rain Mid Morning,
    {{106, 33, 65, 58, 95, 44, 50, 70, 114, 0, 0}, {142, 11, 1, 78, 25, 21, 0, 0, 0, 0, 0}},  // [11] Rain Lunch,
    {{106, 33, 65, 58, 95, 44, 50, 70, 114, 0, 0}, {142, 11, 1, 78, 25, 21, 0, 0, 0, 0, 0}},  // [12] Rain Afternoon,
    {{106, 33, 65, 58, 95, 44, 50, 70, 114, 0, 0}, {142, 11, 1, 78, 25, 21, 0, 0, 0, 0, 0}},  // [13] Rain PM Peak,
    {{106, 33, 65, 58, 95, 44, 50, 70, 78, 0, 0}, {142, 11, 1, 114, 25, 21, 0, 0, 0, 0, 0}},  // [14] Rain Evening,
    {{106, 33, 65, 58, 95, 44, 50, 70, 114, 0, 0}, {142, 1, 78, 25, 0, 0, 0, 0, 0, 0, 0}},  // [15] Rain Night,
    {{106, 33, 65, 58, 95, 44, 50, 70, 78, 0, 0}, {142, 1, 21, 114, 0, 0, 0, 0, 0, 0, 0}},  // [16] Festival Early Morning,
    {{65, 33, 106, 70, 95, 58, 44, 50, 142, 11, 1}, {114, 25, 21, 78, 0, 0, 0, 0, 0, 0, 0}},  // [17] Festival AM Peak,
    {{106, 33, 65, 95, 58, 44, 50, 70, 114, 0, 0}, {142, 11, 1, 21, 25, 78, 0, 0, 0, 0, 0}},  // [18] Festival Mid Morning,
    {{106, 33, 65, 95, 58, 44, 50, 70, 114, 0, 0}, {142, 25, 21, 78, 0, 0, 0, 0, 0, 0, 0}},  // [19] Festival Lunch,
    {{106, 33, 65, 95, 58, 44, 50, 70, 114, 0, 0}, {142, 11, 1, 78, 25, 21, 0, 0, 0, 0, 0}},  // [20] Festival Afternoon,
    {{106, 33, 65, 95, 58, 44, 50, 70, 114, 0, 0}, {142, 1, 78, 25, 21, 0, 0, 0, 0, 0, 0}},  // [21] Festival PM Peak,
    {{106, 33, 65, 58, 95, 44, 50, 70, 78, 0, 0}, {114, 142, 1, 25, 0, 0, 0, 0, 0, 0, 0}},  // [22] Festival Evening,
    {{106, 33, 65, 95, 58, 44, 50, 70, 78, 0, 0}, {142, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},  // [23] Festival Night,
    {{106, 33, 65, 58, 95, 44, 50, 70, 114, 0, 0}, {142, 11, 1, 21, 25, 78, 0, 0, 0, 0, 0}},  // [24] Storm Early Morning,
    {{106, 33, 65, 58, 95, 44, 50, 70, 78, 0, 0}, {142, 11, 1, 21, 25, 114, 0, 0, 0, 0, 0}},  // [25] Storm AM Peak,
    {{106, 33, 65, 58, 95, 44, 50, 70, 78, 0, 0}, {142, 11, 1, 21, 25, 114, 0, 0, 0, 0, 0}},  // [26] Storm Mid Morning,
    {{106, 33, 65, 58, 95, 44, 50, 70, 114, 0, 0}, {142, 11, 1, 78, 21, 25, 0, 0, 0, 0, 0}},  // [27] Storm Lunch,
    {{106, 33, 65, 58, 95, 44, 50, 70, 114, 0, 0}, {142, 11, 1, 78, 25, 21, 0, 0, 0, 0, 0}},  // [28] Storm Afternoon,
    {{106, 33, 65, 58, 95, 44, 50, 70, 78, 0, 0}, {142, 11, 1, 114, 25, 21, 0, 0, 0, 0, 0}},  // [29] Storm PM Peak,
    {{106, 33, 65, 58, 95, 44, 50, 70, 114, 0, 0}, {142, 11, 1, 25, 21, 78, 0, 0, 0, 0, 0}},  // [30] Storm Evening,
    {{106, 70, 33, 65, 58, 95, 44, 50, 142, 114, 0}, {106, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}  // [31] Storm Night
};

static const uint8_t PROGMEM route_lens_pgm[32][2] = {
    {9, 6},  // [ 0] Sunny Early Morning,
    {9, 6},  // [ 1] Sunny AM Peak,
    {9, 6},  // [ 2] Sunny Mid Morning,
    {9, 6},  // [ 3] Sunny Lunch,
    {9, 6},  // [ 4] Sunny Afternoon,
    {9, 6},  // [ 5] Sunny PM Peak,
    {9, 6},  // [ 6] Sunny Evening,
    {9, 1},  // [ 7] Sunny Night,
    {9, 6},  // [ 8] Rain Early Morning,
    {9, 6},  // [ 9] Rain AM Peak,
    {9, 6},  // [10] Rain Mid Morning,
    {9, 6},  // [11] Rain Lunch,
    {9, 6},  // [12] Rain Afternoon,
    {9, 6},  // [13] Rain PM Peak,
    {9, 6},  // [14] Rain Evening,
    {9, 4},  // [15] Rain Night,
    {9, 4},  // [16] Festival Early Morning,
    {11, 4},  // [17] Festival AM Peak,
    {9, 6},  // [18] Festival Mid Morning,
    {9, 4},  // [19] Festival Lunch,
    {9, 6},  // [20] Festival Afternoon,
    {9, 5},  // [21] Festival PM Peak,
    {9, 4},  // [22] Festival Evening,
    {9, 1},  // [23] Festival Night,
    {9, 6},  // [24] Storm Early Morning,
    {9, 6},  // [25] Storm AM Peak,
    {9, 6},  // [26] Storm Mid Morning,
    {9, 6},  // [27] Storm Lunch,
    {9, 6},  // [28] Storm Afternoon,
    {9, 6},  // [29] Storm PM Peak,
    {9, 6},  // [30] Storm Evening,
    {10, 1}  // [31] Storm Night
};

static const uint8_t PROGMEM path_pairs[NUM_PATHS][2] = {
    {1, 21},
    {1, 25},
    {1, 65},
    {1, 78},
    {1, 106},
    {1, 114},
    {11, 1},
    {21, 25},
    {21, 50},
    {21, 78},
    {21, 114},
    {21, 142},
    {25, 21},
    {25, 65},
    {25, 78},
    {25, 114},
    {25, 142},
    {33, 65},
    {33, 70},
    {33, 106},
    {44, 50},
    {44, 142},
    {50, 44},
    {50, 70},
    {50, 142},
    {58, 44},
    {58, 95},
    {65, 33},
    {65, 58},
    {65, 95},
    {70, 33},
    {70, 78},
    {70, 95},
    {70, 114},
    {78, 21},
    {78, 25},
    {78, 106},
    {78, 114},
    {78, 142},
    {95, 21},
    {95, 44},
    {95, 58},
    {106, 33},
    {106, 70},
    {106, 114},
    {114, 25},
    {114, 33},
    {114, 106},
    {114, 142},
    {142, 1},
    {142, 11},
    {142, 25},
    {142, 114}
};

static const uint8_t PROGMEM path_lengths[NUM_PATHS] = {
    21, 25, 23, 29, 35, 29, 11, 17, 7, 29, 21, 19, 17, 15, 29, 9,
    25, 7, 21, 15, 7, 13, 7, 27, 15, 7, 11, 7, 13, 15, 21, 9,
    13, 17, 29, 29, 11, 21, 29, 21, 9, 11, 15, 7, 11, 9, 9, 11,
    29, 13, 13, 25, 29
};

static const uint16_t PROGMEM path_offsets[NUM_PATHS] = {
    0, 21, 46, 69, 98, 133, 162, 173, 190, 197, 226, 247, 266, 283, 298, 327,
    336, 361, 368, 389, 404, 411, 424, 431, 458, 473, 480, 491, 498, 511, 526, 547,
    556, 569, 586, 615, 644, 655, 676, 705, 726, 735, 746, 761, 768, 779, 788, 797,
    808, 837, 850, 863, 888
};

static const uint8_t PROGMEM path_data[TOTAL_PATH_LEN] = {
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
    17, 18, 19, 20, 21, 1, 153, 152, 151, 150, 149, 148, 64, 63, 62, 46,
    47, 48, 49, 50, 131, 130, 129, 128, 127, 126, 22, 23, 24, 25, 1, 153,
    152, 151, 150, 149, 148, 64, 63, 62, 46, 45, 44, 43, 89, 42, 41, 40,
    39, 68, 67, 66, 65, 1, 153, 152, 151, 150, 149, 148, 64, 63, 62, 46,
    45, 44, 43, 89, 90, 91, 92, 93, 94, 95, 85, 84, 83, 82, 81, 80,
    79, 78, 1, 153, 152, 151, 150, 149, 148, 64, 63, 62, 46, 45, 44, 43,
    89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 74, 73,
    72, 103, 104, 105, 106, 1, 153, 152, 151, 150, 149, 148, 64, 63, 62, 46,
    47, 48, 49, 50, 131, 130, 129, 128, 127, 126, 125, 31, 30, 29, 124, 123,
    122, 114, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 21, 20, 19,
    53, 52, 51, 50, 131, 130, 129, 128, 127, 126, 22, 23, 24, 25, 21, 20,
    19, 53, 52, 51, 50, 21, 20, 19, 53, 52, 51, 50, 49, 48, 47, 46,
    45, 44, 43, 89, 90, 91, 92, 93, 94, 95, 85, 84, 83, 82, 81, 80,
    79, 78, 21, 20, 19, 53, 52, 51, 50, 131, 130, 129, 128, 127, 126, 125,
    31, 30, 29, 124, 123, 122, 114, 21, 20, 19, 18, 17, 16, 15, 14, 13,
    141, 140, 139, 138, 137, 146, 145, 144, 143, 142, 25, 24, 23, 22, 126, 127,
    128, 129, 130, 131, 50, 51, 52, 53, 19, 20, 21, 25, 24, 23, 22, 126,
    125, 31, 32, 33, 34, 35, 69, 67, 66, 65, 25, 24, 23, 22, 126, 127,
    128, 55, 56, 57, 58, 59, 60, 88, 89, 90, 91, 92, 93, 94, 95, 85,
    84, 83, 82, 81, 80, 79, 78, 25, 26, 27, 28, 29, 124, 123, 122, 114,
    25, 24, 23, 22, 126, 127, 128, 55, 56, 57, 58, 59, 60, 61, 46, 62,
    63, 64, 148, 147, 146, 145, 144, 143, 142, 33, 34, 35, 69, 67, 66, 65,
    33, 121, 120, 119, 118, 117, 116, 113, 112, 111, 110, 109, 108, 107, 106, 105,
    104, 103, 72, 71, 70, 33, 121, 120, 119, 118, 117, 116, 113, 112, 111, 110,
    109, 108, 107, 106, 44, 45, 46, 47, 48, 49, 50, 44, 45, 46, 62, 63,
    64, 148, 147, 146, 145, 144, 143, 142, 50, 49, 48, 47, 46, 45, 44, 50,
    49, 48, 47, 46, 45, 44, 43, 89, 90, 91, 92, 93, 94, 95, 96, 97,
    98, 99, 100, 101, 102, 74, 73, 72, 71, 70, 50, 49, 48, 47, 46, 62,
    63, 64, 148, 147, 146, 145, 144, 143, 142, 58, 59, 60, 61, 46, 45, 44,
    58, 59, 60, 88, 89, 90, 91, 92, 93, 94, 95, 65, 66, 67, 69, 35,
    34, 33, 65, 66, 67, 68, 39, 40, 41, 42, 89, 88, 60, 59, 58, 65,
    66, 67, 68, 39, 40, 41, 42, 89, 90, 91, 92, 93, 94, 95, 70, 71,
    72, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 116, 117, 118, 119,
    120, 121, 33, 70, 71, 72, 73, 74, 75, 76, 77, 78, 70, 71, 72, 73,
    74, 102, 101, 100, 99, 98, 97, 96, 95, 70, 71, 72, 103, 104, 105, 106,
    107, 108, 109, 110, 111, 112, 113, 116, 115, 114, 78, 79, 80, 81, 82, 83,
    84, 85, 95, 94, 93, 92, 91, 90, 89, 43, 44, 45, 46, 47, 48, 49,
    50, 51, 52, 53, 19, 20, 21, 78, 77, 76, 75, 74, 73, 72, 103, 104,
    105, 106, 107, 108, 109, 110, 111, 112, 113, 116, 115, 114, 122, 123, 124, 29,
    28, 27, 26, 25, 78, 77, 76, 75, 74, 73, 72, 103, 104, 105, 106, 78,
    77, 76, 75, 74, 73, 72, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
    113, 116, 115, 114, 78, 79, 80, 81, 82, 83, 84, 85, 95, 94, 93, 92,
    91, 90, 89, 43, 44, 45, 46, 62, 63, 64, 148, 147, 146, 145, 144, 143,
    142, 95, 94, 93, 92, 91, 90, 89, 43, 44, 45, 46, 47, 48, 49, 50,
    51, 52, 53, 19, 20, 21, 95, 94, 93, 92, 91, 90, 89, 43, 44, 95,
    94, 93, 92, 91, 90, 89, 88, 60, 59, 58, 106, 107, 108, 109, 110, 111,
    112, 113, 116, 117, 118, 119, 120, 121, 33, 106, 105, 104, 103, 72, 71, 70,
    106, 107, 108, 109, 110, 111, 112, 113, 116, 115, 114, 114, 122, 123, 124, 29,
    28, 27, 26, 25, 114, 115, 116, 117, 118, 119, 120, 121, 33, 114, 115, 116,
    113, 112, 111, 110, 109, 108, 107, 106, 114, 122, 123, 124, 29, 30, 31, 125,
    126, 127, 128, 55, 56, 57, 58, 59, 60, 61, 46, 62, 63, 64, 148, 147,
    146, 145, 144, 143, 142, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
    153, 1, 142, 143, 144, 145, 146, 137, 138, 139, 140, 141, 13, 12, 11, 142,
    143, 144, 145, 146, 147, 148, 64, 63, 62, 46, 47, 48, 49, 50, 131, 130,
    129, 128, 127, 126, 22, 23, 24, 25, 142, 143, 144, 145, 146, 147, 148, 64,
    63, 62, 46, 47, 48, 49, 50, 131, 130, 129, 128, 127, 126, 125, 31, 30,
    29, 124, 123, 122, 114
};

// ============================================================
// PROGMEM helper functions
// ============================================================

uint8_t get_demand(uint8_t addr, uint8_t stop_idx) {
    return pgm_read_byte(&demand_data[addr][stop_idx]);
}

uint8_t get_route_stop(uint8_t addr, uint8_t bus, uint8_t step) {
    return pgm_read_byte(&route_stops_pgm[addr][bus][step]);
}

uint8_t get_route_len(uint8_t addr, uint8_t bus) {
    return pgm_read_byte(&route_lens_pgm[addr][bus]);
}

uint8_t get_path_id(uint8_t from_led, uint8_t to_led) {
    for (uint8_t i = 0; i < NUM_PATHS; i++) {
        if (pgm_read_byte(&path_pairs[i][0]) == from_led &&
            pgm_read_byte(&path_pairs[i][1]) == to_led) return i;
    }
    return 0;
}

uint8_t get_path_len(uint8_t path_id) {
    return pgm_read_byte(&path_lengths[path_id]);
}

uint8_t path_rom_lookup(uint8_t path_id, uint8_t step) {
    uint16_t offset = pgm_read_word(&path_offsets[path_id]) + step;
    return pgm_read_byte(&path_data[offset]);
}

uint8_t get_stop_led(uint8_t stop_idx) {
    return pgm_read_byte(&stop_leds[stop_idx]);
}

CRGB get_stop_color(uint8_t addr, uint8_t stop_idx) {
    uint8_t rv        = get_demand(addr, stop_idx);
    uint8_t dl        = rv & 0x03;
    uint8_t bus_bits  = (rv >> 2) & 0x03;
    uint8_t bri;
    switch (dl) {
        case 3:  bri = 255; break;
        case 2:  bri = 176; break;
        case 1:  bri = 112; break;
        default: bri =  48; break;
    }
    // FastLED CRGB(r,g,b); GRB reordering handled by addLeds COLOR_ORDER
    if (bus_bits == 1) return CRGB(0,   0,   bri); // blue  = bus 0/1 route
    if (bus_bits == 2) return CRGB(0,   bri, 0  ); // green = bus 1 route
    return CRGB(5, 5, 5);                           // dim white = inactive
}

// ============================================================
// Bus state machine
// ============================================================

struct Bus {
    uint8_t       state;       // 0=DWELL, 1=TRAVEL
    uint8_t       stop_idx;
    uint8_t       path_id;
    uint8_t       path_step;
    uint8_t       path_len;
    unsigned long dwell_start; // millis() timestamp
    unsigned long move_start;  // millis() timestamp
};

Bus buses[3];
uint8_t cur_addr  = 0;
uint8_t prev_addr = 0xFF;

// Demo mode � always active, cycles through all 32 states (4 scenarios x 8 time slots)
uint8_t       demo_state      = 0;   // 0-31: upper 2 bits = scenario, lower 3 = time slot
unsigned long demo_last_tick  = 0;

CRGB leds[NUM_LEDS];

void reset_bus(uint8_t b, uint8_t start_stop) {
    buses[b].state       = 0;
    buses[b].stop_idx    = start_stop;
    buses[b].path_id     = 0;
    buses[b].path_step   = 0;
    buses[b].path_len    = 1;
    buses[b].dwell_start = millis();
    buses[b].move_start  = millis();
}

// Returns current display LED for a bus (its visual position on the map).
uint8_t get_disp_led(uint8_t b) {
    if (buses[b].state == 0) {
        // DWELL: show the stop LED
        if (b < 2) return get_route_stop(cur_addr, b, buses[b].stop_idx);
        return get_stop_led(buses[b].stop_idx);
    }
    // TRAVEL: show current step along path
    return path_rom_lookup(buses[b].path_id, buses[b].path_step);
}

// Advance stop_idx for bus b (wrapping).  Returns new index.
uint8_t next_stop(uint8_t b) {
    if (b < 2) {
        uint8_t rlen = get_route_len(cur_addr, b);
        return (buses[b].stop_idx + 1 >= rlen) ? 0 : buses[b].stop_idx + 1;
    }
    return (buses[b].stop_idx == 14) ? 0 : buses[b].stop_idx + 1;
}

// Update one bus state machine each loop iteration.
void update_bus(uint8_t b) {
    unsigned long now = millis();

    // Compute current and next stop LEDs (before any state change)
    uint8_t cur_s, nxt_s;
    if (b < 2) {
        cur_s = get_route_stop(cur_addr, b, buses[b].stop_idx);
        uint8_t ni = next_stop(b);
        nxt_s = get_route_stop(cur_addr, b, ni);
    } else {
        cur_s = get_stop_led(buses[b].stop_idx);
        nxt_s = get_stop_led(next_stop(b));
    }
    uint8_t rlen     = (b < 2) ? get_route_len(cur_addr, b) : 15;
    uint8_t jrn_pid  = get_path_id(cur_s, nxt_s);
    uint8_t jrn_len  = get_path_len(jrn_pid);

    if (buses[b].state == 0) { // DWELL
        if (now - buses[b].dwell_start >= DWELL_MS) {
            if (rlen > 1 && jrn_len > 1) {
                // Transition to TRAVEL
                buses[b].path_id    = jrn_pid;
                buses[b].path_len   = jrn_len;
                buses[b].path_step  = 1;       // step 0 = current pos, skip it
                buses[b].stop_idx   = next_stop(b);  // advance to destination
                buses[b].state      = 1;
                buses[b].move_start = now;
            } else {
                buses[b].dwell_start = now;    // re-arm dwell (single-stop route)
            }
        }
    } else { // TRAVEL
        if (now - buses[b].move_start >= MOVE_MS) {
            buses[b].move_start = now;
            if (buses[b].path_step >= buses[b].path_len - 1) {
                // Arrived at destination
                buses[b].state       = 0;
                buses[b].dwell_start = now;
            } else {
                buses[b].path_step++;
            }
        }
    }
}

// ============================================================
// Arduino setup and main loop
// ============================================================

void setup() {
    FastLED.addLeds<LED_TYPE, DATA_PIN, COLOR_ORDER>(leds, NUM_LEDS);
    FastLED.setBrightness(BRIGHTNESS);
    FastLED.clear(true);

    // Spread buses across map at startup
    reset_bus(0,  0);   // Bus 0 (white)  starts at S01
    reset_bus(1,  4);   // Bus 1 (yellow) starts at S05
    reset_bus(2,  9);   // Bus 2 (cyan)   starts at S10
    demo_last_tick = millis();
    cur_addr  = 0;
    prev_addr = 0xFF;
}

void loop() {
    // --- Demo mode: always active, cycles all 32 states every 10 seconds ---
    // Order: SC0/TS0 -> SC0/TS1 -> ... -> SC0/TS7 -> SC1/TS0 -> ... -> SC3/TS7 -> wrap
    unsigned long now = millis();
    if (now - demo_last_tick >= DEMO_INTERVAL_MS) {
        demo_last_tick = now;
        demo_state = (demo_state + 1) & 0x1F;  // cycle 0-31
    }

    uint8_t new_addr = demo_state;  // addr = scenario*8 + timeslot (0-31)
    if (new_addr != prev_addr) {
        prev_addr = new_addr;
        cur_addr  = new_addr;
        // Buses 0 and 1 reset to start of new ML route
        reset_bus(0, 0);
        reset_bus(1, 0);
        // Bus 2 keeps running (independent of ML data)
    }

    // --- Update bus state machines ---
    update_bus(0);
    update_bus(1);
    update_bus(2);

    // --- Build LED frame ---
    // Priority (low to high): background black -> stop colours ->
    //   bus2 cyan -> bus1 yellow -> bus0 white -> LED0 heartbeat
    FastLED.clear();

    // Stop colours
    for (uint8_t i = 0; i < N_STOPS; i++) {
        uint8_t led = get_stop_led(i);
        if (led < NUM_LEDS) leds[led] = get_stop_color(cur_addr, i);
    }

    // Bus overlays
    uint8_t d2 = get_disp_led(2);
    uint8_t d1 = get_disp_led(1);
    uint8_t d0 = get_disp_led(0);
    if (d2 < NUM_LEDS) leds[d2] = CRGB::Cyan;    // bus 2 cyan
    if (d1 < NUM_LEDS) leds[d1] = CRGB::Yellow;  // bus 1 yellow
    if (d0 < NUM_LEDS) leds[d0] = CRGB::White;   // bus 0 white (highest priority)

    // LED 0 heartbeat (shows system is running)
    leds[0] = CRGB(16, 16, 16);

    FastLED.show();
    delay(20);  // ~50 fps
}
